/// Table used to store album notes (many notes per single album)
table AlbumNotes
	lineageTag: 787fb0e1-dfc6-4a0d-92fb-d8072b85a4a4

	/// Primary key
	column pkAlbumNotes
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 873de091-0d76-4ff5-b1f9-211284b99d1e
		summarizeBy: none
		sourceColumn: pkAlbumNotes

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column fkAlbum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e4f856e0-2a8c-4a7f-b2f0-1c6272e4fffe
		summarizeBy: none
		sourceColumn: fkAlbum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AlbumNotes
		dataType: string
		lineageTag: 37631029-de63-4306-a3d8-f0c61db9489d
		summarizeBy: none
		sourceColumn: AlbumNotes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ModDate
		dataType: dateTime
		formatString: General Date
		lineageTag: efc74e7e-b19c-40ed-8b32-530027b1ae57
		summarizeBy: none
		sourceColumn: ModDate

		annotation SummarizationSetBy = Automatic

	column Filedate
		dataType: dateTime
		formatString: General Date
		lineageTag: 61c505ec-7fcb-4cdc-b159-a443e637d995
		summarizeBy: none
		sourceColumn: Filedate

		annotation SummarizationSetBy = Automatic

	partition AlbumNotes = m
		mode: import
		source =
				let
				     Source = Sql.Database("steven-edit-sql.database.windows.net", "Music2026"),
				     #"Tbl" = Source{[Schema = "dbo", Item = "AlbumNotes"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Tbl,{"Album"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

