/// Table used to store Genre Descriptions (unique records)
table Genre
	lineageTag: b9f852f2-6409-4fd1-a9b3-d9ec35799f10

	/// Genre
	column Genre
		dataType: string
		lineageTag: 7c576fa2-3f30-4951-9aba-bc033ad9a19e
		summarizeBy: none
		sourceColumn: Genre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pkGenre
		dataType: int64
		formatString: 0
		lineageTag: 0d055645-5ef8-45d4-bfff-308ca3da5f7d
		summarizeBy: none
		sourceColumn: pkGenre

		annotation SummarizationSetBy = Automatic

	partition Genre = m
		mode: import
		source =
				let
				      Source = Sql.Database("steven-edit-sql.database.windows.net", "Music2026"),
				     #"Nav" = Source{[Schema = "dbo", Item = "Genre"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Nav",{"Include", "FileDate", "ModDate", "TrackList"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

