/// Table used to store name of location where Track/Album purchased from (Retailer)
table PurchasedFrom
	lineageTag: cfc53502-9865-4e8f-97f1-5634c7ca5ba7

	/// PurchasedFrom
	column PurchasedFrom
		dataType: string
		lineageTag: 97fc77ae-01a0-45a4-b3df-51d13ac70224
		summarizeBy: none
		sourceColumn: PurchasedFrom

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Comments
	column Comments
		dataType: string
		lineageTag: 980c1418-98e6-4f12-8627-4379f2522940
		summarizeBy: none
		sourceColumn: Comments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pkPurchasedFrom
		dataType: int64
		formatString: 0
		lineageTag: b2b20da4-8fc2-4181-8982-2b08f1b2f4f1
		summarizeBy: none
		sourceColumn: pkPurchasedFrom

		annotation SummarizationSetBy = Automatic

	column 'Purchased From'
		dataType: string
		lineageTag: 9be6f075-de24-4d38-9155-ee4d07629289
		summarizeBy: none
		sourceColumn: Purchased From

		annotation SummarizationSetBy = Automatic

	partition PurchasedFrom = m
		mode: import
		source =
				let
				     Source = Sql.Database("steven-edit-sql.database.windows.net", "Music2026"),
				    #"Tbl" = Source{[Schema = "dbo", Item = "PurchasedFrom"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(#"Tbl",{"FileDate", "ModDate","AlbumSales","TrackSales"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Columns", "PurchasedFrom", "Purchased From")
				in
				    #"Duplicated Column"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

