/// Table used to store Region and Continent Name
table Region
	lineageTag: 1026b12f-7b1e-45e1-9fdb-39caa750682b

	column pkRegion
		dataType: int64
		formatString: 0
		lineageTag: 530f2e43-12e8-4d08-887a-6634613b9741
		summarizeBy: none
		sourceColumn: pkRegion

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: bafb2bd9-45db-4971-95a4-3f2780037d4f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Continent
		dataType: string
		lineageTag: 0bcbb28a-0d8c-4e07-8ec2-5cda660279f7
		summarizeBy: none
		sourceColumn: Continent

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source =
				let
				   Source = Sql.Database("steven-edit-sql.database.windows.net", "Music2026"),
				    #"Tbl" = Source{[Schema = "dbo", Item = "Region"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Tbl,{"FileDate", "Moddate", "Geography"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

