/// Table used to store Genre Descriptions (unique records)
table Genre
	lineageTag: b9f852f2-6409-4fd1-a9b3-d9ec35799f10

	/// Genre
	column Genre
		dataType: string
		lineageTag: 7c576fa2-3f30-4951-9aba-bc033ad9a19e
		summarizeBy: none
		sourceColumn: Genre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pkGenre
		dataType: int64
		formatString: 0
		lineageTag: 0d055645-5ef8-45d4-bfff-308ca3da5f7d
		summarizeBy: none
		sourceColumn: pkGenre

		annotation SummarizationSetBy = Automatic

	partition Genre = m
		mode: import
		source =
				let
				    //Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery=null, Implementation="2.0", Protocol=null]),
				    Source = Databricks.Catalogs(ServerName, HTTP_PATH, null),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    music2026_gold_Schema = workspace_Database{[Name="music_gold",Kind="Schema"]}[Data],
				    dim_genre_Table = music2026_gold_Schema{[Name="dim_genre",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_genre_Table,{"Include", "skGenre", "FileDate", "ModDate"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

