/// Table used to store Region and Continent Name
table Region
	lineageTag: 1026b12f-7b1e-45e1-9fdb-39caa750682b

	/// Region
	column Region
		dataType: string
		lineageTag: f0d1028b-90b7-4d57-83ef-508238d6c462
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Continent
	column Continent
		dataType: string
		lineageTag: b7a098b6-e775-43dc-8bd3-5b1f729f7809
		summarizeBy: none
		sourceColumn: Continent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pkRegion
		dataType: int64
		formatString: 0
		lineageTag: ca6f281b-3f40-41bc-8185-916472494d33
		summarizeBy: none
		sourceColumn: pkRegion

		annotation SummarizationSetBy = Automatic

	partition Region = m
		mode: import
		source = ```
				let
				    //Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery="disabled", Implementation="2.0", Protocol=null]),
				    Source = Databricks.Catalogs(ServerName, HTTP_PATH, null),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],    
				    music_gold_Schema = workspace_Database{[Name="music_gold",Kind="Schema"]}[Data],
				    dim_region_Table = music_gold_Schema{[Name="dim_region",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_region_Table,{"skRegion", "FileDate", "ModDate"})
				in
				    #"Removed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

