/// Table used to store name of location where Track/Album purchased from (Retailer)
table PurchasedFrom
	lineageTag: cfc53502-9865-4e8f-97f1-5634c7ca5ba7

	/// PurchasedFrom
	column PurchasedFrom
		dataType: string
		lineageTag: 97fc77ae-01a0-45a4-b3df-51d13ac70224
		summarizeBy: none
		sourceColumn: PurchasedFrom

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Comments
	column Comments
		dataType: string
		lineageTag: 980c1418-98e6-4f12-8627-4379f2522940
		summarizeBy: none
		sourceColumn: Comments

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Purchased From'
		dataType: string
		lineageTag: 61447a30-b267-4869-a0b3-012c690d65c2
		summarizeBy: none
		sourceColumn: Purchased From

		annotation SummarizationSetBy = Automatic

	column pkPurchasedFrom
		dataType: int64
		formatString: 0
		lineageTag: b2b20da4-8fc2-4181-8982-2b08f1b2f4f1
		summarizeBy: none
		sourceColumn: pkPurchasedFrom

		annotation SummarizationSetBy = Automatic

	partition PurchasedFrom = m
		mode: import
		source =
				let
				   Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery="disabled", Implementation="2.0", Protocol=null]),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    music2026_gold_Schema = workspace_Database{[Name="music_gold",Kind="Schema"]}[Data],
				    dim_purchasedfrom_Table = music2026_gold_Schema{[Name="dim_purchasedfrom",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_purchasedfrom_Table,{"FileDate", "ModDate"}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Removed Columns", "PurchasedFrom", "PurchasedFrom - Copy"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column",{{"PurchasedFrom - Copy", "Purchased From"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"skPurchasedFrom"})
				in
				    #"Removed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

