/// Table used to store name of the record label where each track is connected to
table RecordLabel
	lineageTag: 9baacb9f-5f7a-443a-be4b-b77d4351f7c5

	/// RecordLabel
	column RecordLabel
		dataType: string
		lineageTag: 1ca87e2d-bf5d-48ce-adde-3272b173ea09
		summarizeBy: none
		sourceColumn: RecordLabel

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column pkRecordLabel
		dataType: int64
		formatString: 0
		lineageTag: c412104f-d6d1-4e93-99b2-2ae6dbdb2f3d
		summarizeBy: none
		sourceColumn: pkRecordLabel

		annotation SummarizationSetBy = Automatic

	partition RecordLabel = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery="disabled", Implementation="2.0", Protocol=null]),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    music_gold_Schema = workspace_Database{[Name="music_gold",Kind="Schema"]}[Data],
				    dim_recordlabel_Table = music_gold_Schema{[Name="dim_recordlabel",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dim_recordlabel_Table,{"skRecordLabel", "FileDate", "ModDate"})
				in
				    #"Removed Columns"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

