/// Table used to store Region and Continent Name
table Region
	lineageTag: 1026b12f-7b1e-45e1-9fdb-39caa750682b

	/// Region
	column Region
		dataType: string
		lineageTag: f0d1028b-90b7-4d57-83ef-508238d6c462
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	/// Continent
	column Continent
		dataType: string
		lineageTag: b7a098b6-e775-43dc-8bd3-5b1f729f7809
		summarizeBy: none
		sourceColumn: Continent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: 00f8855c-af24-4230-934f-e8532f0921f9
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column FileDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 47ab0eb4-40fe-4dd1-9d69-2af95194e4e5
		summarizeBy: none
		sourceColumn: FileDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ModDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4aaee6bc-978c-4d01-9736-24f8997cf6ae
		summarizeBy: none
		sourceColumn: ModDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Region = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery="disabled", Implementation="2.0", Protocol=null]),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    music2026_gold_Schema = workspace_Database{[Name="music2026_gold",Kind="Schema"]}[Data],
				    dim_region_Table = music2026_gold_Schema{[Name="dim_region",Kind="Table"]}[Data],
				    RemoveRegionCaps= Table.TransformColumns(dim_region_Table, {{"Region", Text.Proper, type text}}),
				    RemoveContCaps= Table.TransformColumns(RemoveRegionCaps, {{"Continent", Text.Proper, type text}})
				in
				    RemoveContCaps

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

