/// Table used to store sales of Track Sales
table TrackSales
	lineageTag: d1fe4f8d-bc56-4b65-9185-817afb88c0e2

	/// SalesAmt
	column SalesAmt
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 066d1870-cd15-4f8c-8596-5393a0a0622a
		summarizeBy: none
		sourceColumn: SalesAmt

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// CC
	column CC
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4b9ea7de-38f5-4df1-b2e0-cb6baae807ff
		summarizeBy: none
		sourceColumn: CC

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Bitcoin
	column Bitcoin
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d19e76db-df7a-4ace-9f3a-d7d92ac1be5d
		summarizeBy: none
		sourceColumn: Bitcoin

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	/// Cash
	column Cash
		dataType: double
		lineageTag: 9c8e3e57-6975-4ee7-aab0-8c7d9bae6d89
		summarizeBy: none
		sourceColumn: Cash

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SalesDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4cf3da79-710d-4c0f-8228-d4454fc5b6d9
		summarizeBy: none
		sourceColumn: SalesDate

		annotation SummarizationSetBy = Automatic

	column pkTrackSales
		dataType: int64
		formatString: 0
		lineageTag: 5683af38-b54b-4392-8686-8ee65679cade
		summarizeBy: sum
		sourceColumn: pkTrackSales

		annotation SummarizationSetBy = Automatic

	column SaleCount
		dataType: int64
		formatString: #,0
		lineageTag: dad74495-8e1c-4c40-9b17-69e2c446ed01
		summarizeBy: sum
		sourceColumn: SaleCount

		annotation SummarizationSetBy = Automatic

	column FkTrackList
		dataType: int64
		formatString: 0
		lineageTag: 299925f1-ea10-4ec1-a64a-38edb563ae15
		summarizeBy: none
		sourceColumn: FkTrackList

		annotation SummarizationSetBy = Automatic

	column FkGeographyNo
		dataType: int64
		formatString: 0
		lineageTag: 34d874ad-d6ba-41e1-be57-fedf57b61b7c
		summarizeBy: none
		sourceColumn: FkGeographyNo

		annotation SummarizationSetBy = Automatic

	column FkPurchasedFrom
		dataType: int64
		formatString: 0
		lineageTag: 11433d1c-1034-4607-8c35-e0ea283b4dce
		summarizeBy: none
		sourceColumn: FkPurchasedFrom

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: cc2fa17b-1989-4e8e-968a-b6f07e616ca4
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 86647746-85de-4a41-9e9a-ce35a6863219
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		formatString: 0
		lineageTag: 1162f32f-b601-45ff-b686-712c550c355d
		summarizeBy: sum
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	partition TrackSales = m
		mode: import
		source = ```
				let    
				    Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery="disabled", Implementation="2.0", Protocol=null]),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    music2026_gold_Schema = workspace_Database{[Name="music_gold",Kind="Schema"]}[Data],
				    fact_tracksales_Table = music2026_gold_Schema{[Name="fact_tracksales",Kind="Table"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(fact_tracksales_Table,{"FileDate", "ModDate"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"SalesCount", "SaleCount"}})
				in
				    #"Renamed Columns1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

