table Demographics
	lineageTag: 58a39f59-d175-4288-aab3-a5ca8fdc0867

	measure DemoCount_Selected = ```
			
			
			IF(
			    HASONEVALUE(Demographics[Demographic]),
			    SUM(Demographics[DemoCount]),
			    BLANK()  // or 0, or "Multiple selected"
			)
			
			```
		formatString: 0
		lineageTag: 1e0153b6-9e22-44f6-8c22-3b95cffb8516

		changedProperty = IsHidden

	measure DemoCountM = ```
			
			    SUM(Demographics[DemoCount])
			
			
			```
		formatString: 0
		lineageTag: 708aebfa-6e34-4650-b31d-37398f6a75d6

		changedProperty = IsHidden

	measure DemoCount_Tornado =
			
			VAR Gender = SELECTEDVALUE(Demographics[Gender])
			VAR CountM = Demographics[DemoCountM]
			RETURN
			IF(Gender = "Male", -CountM, CountM)
		formatString: #,0
		lineageTag: 18928e72-1e34-4255-a681-0f7f589705b6

		changedProperty = IsHidden

	measure DynamicDemoCount =
			
			VAR SelCount = COUNTROWS( VALUES( 'TrackList'[Track - Artist] ) )
			VAR ThisValue = Demographics[DemoCount_Tornado]
			VAR AvgAll = CALCULATE(
			    AVERAGEX(
			        VALUES( 'TrackList'[Track - Artist] ),
			        Demographics[DemoCount_Tornado]
			    ),
			    ALL( 'TrackList'[Track - Artist] )
			)
			VAR AvgSelected = AVERAGEX(
			    VALUES( 'TrackList'[Track - Artist] ),
			    Demographics[DemoCount_Tornado]
			)
			VAR Result = SWITCH(
			    TRUE(),
			    SelCount = 0, AvgAll,
			    SelCount = 1, ThisValue,
			    SelCount > 1, AvgSelected,
			    BLANK()
			)
			RETURN
			    IF(Result = 0, BLANK(), Result)
		lineageTag: ea0e1738-0cf5-4e62-8db4-96d17a5dfec7

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column pkDemo
		dataType: int64
		formatString: 0
		lineageTag: 6e00348b-0529-40b6-a24f-12fd87c86c48
		summarizeBy: none
		sourceColumn: pkDemo

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column fkTrackList
		dataType: int64
		formatString: 0
		lineageTag: f0a29a93-7258-4757-b82e-065625563b8f
		summarizeBy: none
		sourceColumn: fkTrackList

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Demographic
		dataType: string
		lineageTag: 16e19e4d-3104-4938-befb-8ce7b4bfafb0
		summarizeBy: none
		sourceColumn: Demographic

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DemoCount
		dataType: int64
		formatString: 0
		lineageTag: 70fe3e6a-13f6-4b5b-8345-ef40a728c454
		summarizeBy: none
		sourceColumn: DemoCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Gender =
			
			IF(
			    LEFT(Demographics[Demographic], 1) = "F",
			    "Women",
			    "Men"
			)
		lineageTag: 486d5a33-29ac-40a8-8ba3-be251174b7c7
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AgeGroup = ```
			
			VAR demo = Demographics[Demographic]
			RETURN
			SWITCH(
			    TRUE(),
			    LEFT(demo, 7) = "Females", MID(demo, 8, LEN(demo) - 7),
			    LEFT(demo, 5) = "Males", MID(demo, 6, LEN(demo) - 5),
			    BLANK()
			)
			
			```
		lineageTag: cb791adb-a72f-4f7a-be42-7fd4a36bf5d7
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DemoCount_Tornado_Column = ```
			
			IF(
			    Demographics[Gender] = "Male",
			    -Demographics[DemoCount],
			    Demographics[DemoCount]
			)
			
			```
		formatString: 0
		lineageTag: b32cd07a-a276-423a-9902-ceec9c21a741
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column DemoLabel = ```
			
			VAR demo = Demographics[Demographic]
			VAR gender = 
			    SWITCH(TRUE(),
			        LEFT(demo, 7) = "Females", "Women",
			        LEFT(demo, 5) = "Males", "Men",
			        BLANK()
			    )
			VAR rawAge = 
			    SWITCH(TRUE(),
			        LEFT(demo, 7) = "Females", MID(demo, 8, LEN(demo) - 7),
			        LEFT(demo, 5) = "Males", MID(demo, 6, LEN(demo) - 5),
			        BLANK()
			    )
			VAR formattedAge = 
			    SWITCH(TRUE(),
			        rawAge = "18", "18",
			        rawAge = "1834", "18–34",
			        rawAge = "3454", "34–54",
			        rawAge = "54+", "54+",
			        rawAge // fallback
			    )
			RETURN
			    IF(NOT(ISBLANK(gender)) && NOT(ISBLANK(formattedAge)),
			        gender & " " & formattedAge,
			        BLANK()
			    )
			
			```
		lineageTag: 3b57047b-3623-4704-a1d0-161ce097d392
		summarizeBy: none
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SortOrder =
			
			SWITCH(
			    Demographics[Demographic],
			    "Males18", 1,
			    "Females18", 2,
			    "Females1834", 3,
			    "Males1834", 4,
			    "Females3454", 5,
			    "Males3454", 6,
			    "Females54", 7,
			    "Males54", 8,
			    99
			)
		formatString: 0
		lineageTag: bb94b05b-248c-455a-b33e-1a6c8e370c38
		summarizeBy: none

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'DemoCount - Copy'
		dataType: string
		lineageTag: 66290c8b-2e51-43bd-8aab-a6af72481927
		summarizeBy: none
		sourceColumn: DemoCount - Copy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Demographic - Slicer'
		dataType: string
		lineageTag: 63da9ac1-9188-4f36-b2e5-1182bb810c9f
		summarizeBy: none
		sourceColumn: Demographic - Slicer

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Demographics = m
		mode: import
		source =
				let
				    Source = Sql.Database(ServerName, DBName, [Query="SELECT [pkDemo]#(lf)      ,[fkTrackList]#(lf)      ,[Males18]#(lf)      ,[Males1834]#(lf)      ,[Males3454]#(lf)      ,[Males54]#(lf)      ,[Females18]#(lf)      ,[Females1834]#(lf)      ,[Females3454]#(lf)      ,[Females54]#(lf)      --,[FileDate]#(lf)      --,[ModDate]#(lf)  FROM [Music2024].[dbo].[Demos]"]),
				    MarkedKeys = Table.AddKey(Source, {"pkDemo"}, true),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(Source, {"pkDemo", "fkTrackList"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Demographic"}, {"Value", "DemoCount"}}),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Renamed Columns", "DemoCount", "DemoCount - Copy"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Duplicated Column",{{"DemoCount - Copy", type text}}),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Changed Type", "Demographic", "Demographic - Copy"),
				    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column1",{{"Demographic - Copy", "Demographic - Slicer"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Males54","Men 54+",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Males54","Men 54+",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Females54","Women 54+",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Females3454","Women 34-54",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Males1834","Men 18-34",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Males3454","Men 34-54",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Females1834","Women 18-34",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Replaced Value6","Females18","Women 18",Replacer.ReplaceText,{"Demographic - Slicer"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Males18","Men 18",Replacer.ReplaceText,{"Demographic - Slicer"})
				in
				    #"Replaced Value8"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

