/// Table used to store sales of albums
table AlbumSales
	lineageTag: 4efc2010-3cf2-48b9-ad78-66e8d8436f80

	/// Primary key
	column AlbumSalesID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b486a2d6-915c-45d1-9eef-75a097961256
		summarizeBy: none
		sourceColumn: AlbumSalesID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column fkAlbum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 86b4a5b6-79d2-4824-a7ef-8cdac796f00c
		summarizeBy: none
		sourceColumn: fkAlbum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column fkGeographyNo
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5cc7b1e6-06c5-4f7a-8a0f-b97e64c1297b
		summarizeBy: none
		sourceColumn: fkGeographyNo

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Salesdate
		dataType: dateTime
		formatString: General Date
		lineageTag: 3cf581e5-8294-4016-87a5-5bea26756271
		summarizeBy: none
		sourceColumn: Salesdate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SaleCount
		dataType: int64
		formatString: #,0
		lineageTag: cec99f73-1b5d-406c-8ebc-745b87248118
		summarizeBy: none
		sourceColumn: SaleCount

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column SalesAmt
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 051768ca-a552-4166-baaa-083b29eea9d6
		summarizeBy: none
		sourceColumn: SalesAmt

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column fkPurchasedFrom
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 555d6c08-79a1-430f-a0e2-523e9edc853a
		summarizeBy: none
		sourceColumn: fkPurchasedFrom

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CC
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: cc6feb17-3758-467b-a8eb-4e42c7494b3c
		summarizeBy: none
		sourceColumn: CC

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Bitcoin
		dataType: double
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 83900480-18d5-42df-92ea-16936a772f40
		summarizeBy: none
		sourceColumn: Bitcoin

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Cash
		dataType: double
		lineageTag: 3651a829-d543-44e3-bbf4-9548f83daa84
		summarizeBy: none
		sourceColumn: Cash

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition AlbumSales = m
		mode: import
		source =
				let
				    Source = Sql.Database(ServerName, DBName, [Query="        SELECT #(lf)          [pkAlbumSales]#(lf)         ,[fkAlbum]#(lf)         ,[fkGeographyNo]#(lf)         ,[Salesdate]#(lf)         ,[SaleCount]#(lf)         ,[SalesAmt]#(lf)         ,[fkPurchasedFrom]#(lf)         ,[CC]#(lf)         ,[Bitcoin]#(lf)         ,Cash#(lf)      FROM #(lf)         [Music2024].[dbo].[AlbumSales]#(lf)--where [Salesdate] >= '11/1/2024 12:00:00 AM'", CommandTimeout=#duration(0, 0, 10, 0)]),
				        MarkedKeys = Table.AddKey(Source, {"pkAlbumSales"}, true),
				    Custom1 = MarkedKeys,
				    #"Renamed Columns" = Table.RenameColumns(Custom1,{{"pkAlbumSales", "AlbumSalesID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

