/// Table used to store album notes (many notes per single album)
table AlbumNotes
	lineageTag: 787fb0e1-dfc6-4a0d-92fb-d8072b85a4a4

	/// Primary key
	column AlbumNotesID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 873de091-0d76-4ff5-b1f9-211284b99d1e
		summarizeBy: none
		sourceColumn: AlbumNotesID

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column fkAlbum
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: e4f856e0-2a8c-4a7f-b2f0-1c6272e4fffe
		summarizeBy: none
		sourceColumn: fkAlbum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AlbumNotes
		dataType: string
		lineageTag: 37631029-de63-4306-a3d8-f0c61db9489d
		summarizeBy: none
		sourceColumn: AlbumNotes

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition AlbumNotes = m
		mode: import
		source =
				let
				    Source = Sql.Database(ServerName, DBName,
				    [Query="SELECT #(lf)     [pkAlbumNotes]#(lf)     ,[fkAlbum]#(lf)     ,[AlbumNotes]#(lf)  FROM #(lf)     [Music2024].[dbo].[AlbumNotes]"]),
				    MarkedKeys = Table.AddKey(Source, {"pkAlbumNotes"}, true),
				    #"Renamed Columns" = Table.RenameColumns(MarkedKeys,{{"pkAlbumNotes", "AlbumNotesID"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

