/// Table used to store Genre Descriptions (unique records)
table Genre
	lineageTag: b9f852f2-6409-4fd1-a9b3-d9ec35799f10

	/// Genre
	column Genre
		dataType: string
		lineageTag: 7c576fa2-3f30-4951-9aba-bc033ad9a19e
		summarizeBy: none
		sourceColumn: Genre

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column GenreID
		dataType: int64
		formatString: 0
		lineageTag: 9cde5b2c-56d3-404b-9ad9-b6418106505b
		summarizeBy: none
		sourceColumn: GenreID

		annotation SummarizationSetBy = Automatic

	column FileDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3ee0429c-7de0-4a0a-8631-149c46af597c
		summarizeBy: none
		sourceColumn: FileDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column ModDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c2950d9c-16cf-4081-8d7f-9e8c86324c6f
		summarizeBy: none
		sourceColumn: ModDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Genre = m
		mode: import
		source =
				let
				    Source = Databricks.Catalogs("dbc-889876c1-2aee.cloud.databricks.com", "/sql/1.0/warehouses/4a6aab97cf7a86de", [Catalog=null, Database=null, QueryTags=null, EnableAutomaticProxyDiscovery="disabled", Implementation="2.0", Protocol=null]),
				    workspace_Database = Source{[Name="workspace",Kind="Database"]}[Data],
				    music2026_gold_Schema = workspace_Database{[Name="music2026_gold",Kind="Schema"]}[Data],
				    dim_genre_Table = music2026_gold_Schema{[Name="dim_genre",Kind="Table"]}[Data],
				    RemoveCapitalization= Table.TransformColumns(dim_genre_Table, {{"Genre", Text.Proper, type text}})
				in
				    RemoveCapitalization

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

